import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { initializeFirestore, collection, getDocs, getDoc, doc, addDoc, setDoc, updateDoc, deleteDoc, serverTimestamp, query, orderBy, where } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig);const db=initializeFirestore(app,{experimentalForceLongPolling:true});const auth=getAuth(app);const $=s=>document.querySelector(s);const adminEmail='YOUR_ADMIN_EMAIL';
const fields={id:$('#postId'),title:$('#postTitle'),category:$('#postCategory'),status:$('#postStatus'),slug:$('#postSlug'),excerpt:$('#postExcerpt'),image:$('#postImage'),author:$('#postAuthor'),readTime:$('#postReadTime'),tags:$('#postTags'),body:$('#postBody')};
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('#tab-'+name).classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='posts')loadPosts();if(name==='subscribers')loadSubscribers();if(name==='comments')loadComments();if(name==='appearance')loadAppearance()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#newPost').onclick=()=>{fields.id.value='';document.querySelector('#postForm').reset();fields.author.value='Vertex Theory';fields.readTime.value='5 min read';$('#deletePost').classList.add('hidden');$('#editorTitle').textContent='New post';tab('editor')};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value)}catch(err){$('#loginError').textContent='Sign-in failed. Check your credentials and Firebase Auth setup.';$('#loginError').classList.remove('hidden')}};$('#logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{if(!u){$('#loginView').classList.remove('hidden');$('#adminView').classList.add('hidden');return}if(adminEmail!=='YOUR_ADMIN_EMAIL'&&u.email!==adminEmail){signOut(auth);$('#loginError').textContent='This account is not the configured administrator.';$('#loginError').classList.remove('hidden');return}$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#who').textContent=u.email;loadPosts();});
async function loadPosts(){const snap=await getDocs(query(collection(db,'posts'),orderBy('createdAt','desc')));$('#postList').innerHTML=snap.docs.map(d=>{const p=d.data();return `<div class="post-row"><div><strong>${esc(p.title)}</strong><div class="meta">${esc(p.category||'')} · ${esc(p.status||'draft')}</div></div><button class="button" data-edit="${d.id}">Edit</button></div>`}).join('')||'<p class="meta">No posts yet.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit))}
async function editPost(id){const s=await getDoc(doc(db,'posts',id));if(!s.exists())return;const p=s.data();fields.id.value=id;for(const k of ['title','category','status','slug','excerpt','image','author','readTime','body'])fields[k].value=p[k]||'';fields.tags.value=(p.tags||[]).join(', ');$('#deletePost').classList.remove('hidden');$('#editorTitle').textContent='Edit post';tab('editor')}
$('#postForm').onsubmit=async e=>{e.preventDefault();const data={title:fields.title.value.trim(),category:fields.category.value.trim(),status:fields.status.value,slug:fields.slug.value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,''),excerpt:fields.excerpt.value.trim(),image:imgur(fields.image.value.trim()),author:fields.author.value.trim()||'Vertex Theory',readTime:fields.readTime.value.trim()||'5 min read',tags:fields.tags.value.split(',').map(x=>x.trim()).filter(Boolean),body:fields.body.value,updatedAt:serverTimestamp()};try{if(fields.id.value){await updateDoc(doc(db,'posts',fields.id.value),data)}else{data.createdAt=serverTimestamp();if(data.status==='published')data.publishedAt=serverTimestamp();await addDoc(collection(db,'posts'),data)}toast('Post saved.');tab('posts')}catch(err){toast('Could not save post. Check Firestore rules.')}};
$('#deletePost').onclick=async()=>{if(!fields.id.value)return;if(confirm('Delete this post permanently?')){await deleteDoc(doc(db,'posts',fields.id.value));toast('Deleted.');tab('posts')}};
async function loadAppearance(){const s=await getDoc(doc(db,'settings','site'));const p=s.exists()?s.data():{};$('#siteTitle').value=p.siteTitle||'Vertex Theory';$('#siteDescription').value=p.description||'';$('#accent').value=p.accent||'#c64b2d';$('#accent2').value=p.accent2||'#243d35'}$('#appearanceForm').onsubmit=async e=>{e.preventDefault();try{await setDoc(doc(db,'settings','site'),{siteTitle:$('#siteTitle').value.trim()||'Vertex Theory',description:$('#siteDescription').value.trim(),accent:$('#accent').value,accent2:$('#accent2').value,updatedAt:serverTimestamp()},{merge:true});toast('Appearance saved.')}catch(err){toast('Could not save appearance.')}};

async function loadComments(){const wrap=$('#commentList');try{const postsSnap=await getDocs(collection(db,'posts'));const rows=[];for(const pd of postsSnap.docs){const p=pd.data();const snap=await getDocs(query(collection(db,'posts',pd.id,'comments'),orderBy('createdAt','desc')));snap.docs.forEach(cd=>rows.push({id:cd.id,postId:pd.id,postTitle:p.title||'Untitled',...cd.data()}))}rows.sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));wrap.innerHTML=rows.map(c=>`<div class="post-row"><div><strong>${esc(c.name)}</strong><div class="meta">${esc(c.postTitle)} · ${esc(c.status||'pending')}</div><p>${esc(c.comment)}</p></div><div style="display:flex;gap:7px;align-items:start;flex-wrap:wrap">${c.status!=='approved'?`<button class="button" data-approve="${c.postId}|${c.id}">Approve</button>`:''}<button class="button danger" data-del-comment="${c.postId}|${c.id}">Delete</button></div></div>`).join('')||'<p class="meta">No comments yet.</p>';document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{const [postId,id]=b.dataset.approve.split('|');await updateDoc(doc(db,'posts',postId,'comments',id),{status:'approved',moderatedAt:serverTimestamp()});loadComments()});document.querySelectorAll('[data-del-comment]').forEach(b=>b.onclick=async()=>{const [postId,id]=b.dataset.delComment.split('|');if(confirm('Delete this comment?')){await deleteDoc(doc(db,'posts',postId,'comments',id));loadComments()}})}catch(e){console.error(e);wrap.innerHTML='<p class="error">Could not load comments.</p>'}}
async function loadSubscribers(){const snap=await getDocs(query(collection(db,'subscribers'),orderBy('createdAt','desc')));$('#subscriberList').innerHTML=snap.docs.map(d=>`<div class="post-row"><div><strong>${esc(d.data().email)}</strong><div class="meta">${d.data().createdAt?.toDate?.().toLocaleString()||''}</div></div><button class="button danger" data-del-sub="${d.id}">Delete</button></div>`).join('')||'<p class="meta">No subscribers yet.</p>';document.querySelectorAll('[data-del-sub]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,'subscribers',b.dataset.delSub));loadSubscribers()})}
function imgur(url){if(!url)return '';try{const u=new URL(url);if(!u.hostname.includes('imgur.com'))return url;if(u.hostname==='i.imgur.com')return url;let id=u.pathname.split('/').filter(Boolean).pop().replace(/\.(jpg|jpeg|png|gif|webp)$/i,'');return id?`https://i.imgur.com/${id}.jpg`:url}catch{return url}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
